services:
  frontend:
    build:
      context: ./my-crm-react-app
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
  backend:
    build:
      context: ./my-crm-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
        db:
          condition: service_healthy

    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=${DB_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${DB_PASSWORD}
    env_file: .env

  db:
    image: mysql:8.0
    environment:
    
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 5
